- src/mainboard/system76/cfl-h/devicetree.cb
- src/mainboard/system76/cfl-h/dsdt.asl
- src/mainboard/system76/cml-u/devicetree.cb
- src/mainboard/system76/cml-u/dsdt.asl
- src/mainboard/system76/cml-u/ramstage.c
- src/mainboard/system76/kbl-u/dsdt.asl
- src/mainboard/system76/thelio-b1/devicetree.cb
- src/mainboard/system76/thelio-b1/dsdt.asl
- src/mainboard/system76/whl-u/devicetree.cb
- src/mainboard/system76/whl-u/dsdt.asl
- src/mainboard/system76/whl-u/ramstage.c
Fixes building on darp5, darp6, galp3-c, and galp4.
thelio-b1 and kbl-u updated for consistency.
> mainboard/system76: Fix compiling other boards on 4.12

- src/mainboard/system76/gaze14/devicetree.cb
- src/mainboard/system76/gaze15/devicetree.cb
The USB table in the manuals incorrectly list the USB3 port as 5. The labeled pins show it correctly as port 2.
> mb/system76: Fix left USB3 port on gaze14/gaze15

- src/mainboard/system76/addw2/Kconfig
- src/mainboard/system76/cml-u/Kconfig
- src/mainboard/system76/gaze14/Kconfig
- src/mainboard/system76/gaze15/Kconfig
- src/mainboard/system76/kbl-u/Kconfig
- src/mainboard/system76/lemp9/Kconfig
- src/mainboard/system76/oryp6/Kconfig
- src/mainboard/system76/thelio-b1/Kconfig
- src/mainboard/system76/whl-u/Kconfig
`FSP_M_XIP` is already selected by the soc.
Ref: 48833363daef0 ("mb/system76/lemp9: drop FSP_M_XIP")
> mb/system76: Remove FSP_M_XIP

- src/mainboard/system76/gaze15/devicetree.cb
Based on the updated schematics, ports 7 (previously annotated as 3G) and 9 (previously Per-key RGB) are not connected, and port 10 is connected to the fingerprint reader.
> mb/system76/gaze15: Correct registers for USB ports

- src/mainboard/system76/addw1/romstage.c
- src/mainboard/system76/addw2/romstage.c
- src/mainboard/system76/bonw14/romstage.c
- src/mainboard/system76/cml-u/romstage.c
- src/mainboard/system76/gaze14/romstage.c
- src/mainboard/system76/gaze15/romstage.c
- src/mainboard/system76/lemp9/romstage.c
- src/mainboard/system76/oryp5/romstage.c
- src/mainboard/system76/oryp6/romstage.c
- src/mainboard/system76/thelio-b1/romstage.c
- src/mainboard/system76/whl-u/romstage.c
- Remove the comments, which were copied from the header
- Remove the dq entries for LPDDR, which are not used
- Allow higher memory speeds on oryp5
> mb/system76: Simplify romstage.c

- src/mainboard/system76/addw1/devicetree.cb
- src/mainboard/system76/addw2/devicetree.cb
- src/mainboard/system76/bonw14/devicetree.cb
- src/mainboard/system76/cml-u/devicetree.cb
- src/mainboard/system76/gaze14/devicetree.cb
- src/mainboard/system76/gaze15/devicetree.cb
- src/mainboard/system76/kbl-u/devicetree.cb
- src/mainboard/system76/oryp5/devicetree.cb
- src/mainboard/system76/oryp6/devicetree.cb
- src/mainboard/system76/thelio-b1/devicetree.cb
- src/mainboard/system76/whl-u/devicetree.cb
Upstream is moving towards having registers set within their relevant device. Do this now to reduce the diff for upstreaming and later syncing changes back.
Does not touch the TGL boards or lemp9, which have most of the changes.
- Move registers to devices
- Remove unneeded registers
- Remove extra comments
TODO: Move all of those comments from each board to the docs and/or a script.
> Update devicetrees based on upstream

- src/mainboard/system76/addw1/ramstage.c
- src/mainboard/system76/addw2/ramstage.c
- src/mainboard/system76/bonw14/ramstage.c
- src/mainboard/system76/cml-u/ramstage.c
- src/mainboard/system76/gaze14/ramstage.c
- src/mainboard/system76/gaze15/ramstage.c
- src/mainboard/system76/oryp5/ramstage.c
- src/mainboard/system76/oryp6/ramstage.c
- src/mainboard/system76/thelio-b1/ramstage.c
Replace FSP hack with mainboard_ops .init() on CFL/CML.
> mb/system76: Remove use of cnl_configure_pads()

- src/mainboard/system76/addw1/devicetree.cb
- src/mainboard/system76/addw2/devicetree.cb
- src/mainboard/system76/bonw14/devicetree.cb
- src/mainboard/system76/cml-u/variants/darp6/overridetree.cb
- src/mainboard/system76/gaze14/devicetree.cb
- src/mainboard/system76/gaze15/gpio.h
- src/mainboard/system76/lemp9/devicetree.cb
- src/mainboard/system76/oryp6/devicetree.cb
- src/mainboard/system76/whl-u/variants/darp5/overridetree.cb
Per upstream [\[1\]], HID over I2C must be level triggered.
[\[1\]]: https://review.coreboot.org/c/coreboot/+/50452
> mb/system76: Configure HID IRQs as level triggered

- src/mainboard/system76/addw1/devicetree.cb
- src/mainboard/system76/addw2/devicetree.cb
- src/mainboard/system76/bonw14/devicetree.cb
- src/mainboard/system76/cml-u/variants/darp6/overridetree.cb
- src/mainboard/system76/gaze14/devicetree.cb
- src/mainboard/system76/lemp9/devicetree.cb
- src/mainboard/system76/oryp6/devicetree.cb
- src/mainboard/system76/whl-u/variants/darp5/overridetree.cb
This reverts commit c1e02290948e7cf34ed5b9a6d80a167ab0956023.
This change breaks the touchpad on oryp6. We will change these as-needed if it proves to resolve issues, not just because Microsoft says so.
> Revert "mb/system76: Configure HID IRQs as level triggered"

- src/mainboard/system76/gaze15/devicetree.cb
This adds the ELAN touchpad settings from the lemp10 in an attempt to support ELAN touchpads on the gaze15.
**Please see https://github.com/system76/firmware-open/pull/181 for testing**
> gaze15: Add ELAN touchpad settings

- src/mainboard/system76/addw1/acpi/mainboard.asl
- src/mainboard/system76/addw2/acpi/mainboard.asl
- src/mainboard/system76/cml-u/acpi/mainboard.asl
- src/mainboard/system76/gaze14/acpi/mainboard.asl
- src/mainboard/system76/gaze15/acpi/mainboard.asl
- src/mainboard/system76/lemp9/acpi/mainboard.asl
- src/mainboard/system76/oryp5/acpi/mainboard.asl
- src/mainboard/system76/oryp6/acpi/mainboard.asl
- src/mainboard/system76/oryp7/acpi/mainboard.asl
- src/mainboard/system76/whl-u/acpi/mainboard.asl
The `EC_COLOR_KEYBOARD` define is not used by the EC ASL. A Kconfig selection is used instead.
> mb/system76: acpi: Remove unused define

- src/soc/intel/cannonlake/Kconfig
- src/soc/intel/cannonlake/me.c
- src/soc/intel/tigerlake/Kconfig
- src/soc/intel/tigerlake/me.c
Replace hard-coded value with a Kconfig option, enabled on CNL to preserve behavior.
Add it to TGL as well, defaulting to disabled to avoid the S0ix issue.
> Add Kconfig for disabling IME

- src/mainboard/system76/addw1/cmos.layout
- src/mainboard/system76/addw2/cmos.layout
- src/mainboard/system76/bonw14/cmos.layout
- src/mainboard/system76/cml-u/cmos.layout
- src/mainboard/system76/darp7/cmos.layout
- src/mainboard/system76/galp5/cmos.layout
- src/mainboard/system76/gaze14/cmos.layout
- src/mainboard/system76/gaze15/cmos.layout
- src/mainboard/system76/kbl-u/cmos.layout
- src/mainboard/system76/lemp10/cmos.layout
- src/mainboard/system76/lemp9/cmos.layout
- src/mainboard/system76/oryp5/cmos.layout
- src/mainboard/system76/oryp6/cmos.layout
- src/mainboard/system76/oryp7/cmos.layout
- src/mainboard/system76/whl-u/cmos.layout
`DisplayPort_Output` conflicts with `RTC_BOOT_BYTE`. Move it to 392 and adjust the checksum to start there as well.
Modify enum index for `debug_level` and `boot_option` to match other boards across coreboot.
> mb/system76: Fix CMOS layouts

- src/mainboard/system76/darp7/devicetree.cb
- src/mainboard/system76/galp5/devicetree.cb
- src/mainboard/system76/gaze16/variants/3050/overridetree.cb
- src/mainboard/system76/gaze16/variants/3060/overridetree.cb
- src/mainboard/system76/lemp10/devicetree.cb
- src/soc/intel/tigerlake/fsp_params.c
Cherry-pick f3c4f29ddda to fix subsystem IDs on TGL. Add subsystem IDs to TGL boards.
Check subsystem IDs with `lspci -vnn`.
> mb/system76/*: Add subsystemid to TGL models

- src/mainboard/system76/galp5/acpi/dgpu.asl
- src/mainboard/system76/gaze16/acpi/dgpu.asl
Save NVIDIA device subsystem ID before turning off the GPU, and restore
it after turning on the GPU. This prevents to GPU from having the
default 10de:0000 SSID on RTD3 _ON.
Fixes formatting and device scope.
Tested on gaze16-3050 by checking lspci after RTD3 _OFF.
$ cat /sys/bus/pci/devices/0000\:01\:00.0/power/runtime_status
suspended
$ lspci -s 01:00.0 -vnn | grep Subsystem
Subsystem: CLEVO/KAPOK Computer GA107M [GeForce RTX 3050 Mobile] [1558:5015]
Ref: system76/firmware-open#231
> mb/system76/{galp5,gaze16}: acpi: Save/Restore NVIDIA SSID

- src/soc/intel/tigerlake/gpio_pch_h.c
Update GPIOs based on changes to Linux kernel.
Might fix system76/firmware-open#226
Ref: torvalds/linux@2f658f7a395
> soc/intel/tgl: Fix GPIO mapping for TGL-H

- src/ec/system76/ec/acpi/battery.asl
- src/ec/system76/ec/acpi/ec_ram.asl
After noticing that cycle count wasn't reported with our firmware (after seeing https://gitlab.freedesktop.org/upower/upower/-/issues/152), I thought I'd see what it takes to implement and try to better understand how this works at a firmware level.
Not sure exactly what value to expect, but `/sys/class/power_supply/BAT0/cycle_count` reports a non-zero value now, and draining my battery made it go up by one, so it seems to be working.
Requires https://github.com/system76/ec/pull/243.
> ec/system76/ec: Implement `_BIX` acpi method, exposing cycle count

- src/soc/intel/tigerlake/Kconfig
Fix backlight controls on TGL?
Checked with `intel_reg` on gaze16 when using `default_brightness_table.asl`.
```
$ sudo intel_reg read 0xc8254
(0x000c8254): 0x0000bb80 (freq 0, cycle 48000)
$ cat /sys/class/backlight/intel_backlight/max_brightness 
48000
```
```
$ sudo intel_reg read 0xc8258
(0x000c8258): 0x0000102d
$ cat /sys/class/backlight/intel_backlight/brightness 
1399
$ sudo intel_reg read 0xc8258
(0x000c8258): 0x00005d62
$ cat /sys/class/backlight/intel_backlight/brightness 
22400
```
upstream: [CB:57823](https://review.coreboot.org/c/coreboot/+/57823)
> soc/intel/tigerlake: Add values for GMA registers

- src/mainboard/system76/gaze16/devicetree.cb
Fix using USB 2.0 devices via an adapter in the Type-C port.
Resolves: system76/firmware-open#242
> mb/system76/gaze16: Enable TCSS xHCI

- src/soc/intel/common/block/memory/meminit.c
Revert from `die()` to `printk()` if SPD lengths are different for mixed memory topology. Fixes booting system76/lemp10 when a DIMM is not present.
Resolves: system76/firmware-open#269
---
On `system76-4.13` the DIMM SPD size would get detected as 256 when not present.
> No memory dimm at address A4
> Mixed topology has incorrect length: 512 != 256.
> soc/intel/common/memory: Don't die if SPD lengths differ

- src/soc/intel/common/block/memory/meminit.c
From: [CB:60800](https://review.coreboot.org/c/coreboot/+/60800/)
When using a mixed memory topology with DDR4, it's not possible to boot
when no DIMMs are installed, even though memory-down is available. This
happens because the DIMM SPD length defaults to 256 when no DIMM SPD is
available. Relax the length check when no DIMMs are present to overcome
this problem.
> soc/intel/common/blk/memory: Make mixed topo work

- src/soc/intel/tigerlake/fsp_params.c
Fixes IRQ errors on oryp8 that cause conflicts with the PCH HDA device.
```
pcieport 0000:00:01.0: can't derive routing for PCI INT A
pcieport 0000:00:01.0: can't derive routing for PCI INT B
```
```
irq 10: nobody cared (try booting with the "irqpoll" option)
...
[<00000000fb84c354>] azx_interrupt [snd_hda_codec]
Disabling IRQ #10
```
Must be tested on all TGL boards. On TGL-U, these ports are used for the SSD, so SSD slots must be populated.
> soc/intel/tgl: Add PEG devices to IRQ constraints

- src/mainboard/system76/adl-p/variants/lemp11/overridetree.cb
lemp11 is ADL-U, not ADL-P. Use the correct ID to override the values and reduce PL1 to the TDP of 15W.
Check values with cbmem:
```
cd util/cbmem
make
sudo ./cbmem -c > cbmem.txt
grep -E 'CPU (TDP|PL)' cbmem.txt
```
Tested by checking system remains on when:
- Logging in to GDM
- Building firmware-open
- Building the Linux kernel
Which previously could cause an i7 unit to power off.
> mb/system76/adl-p: lemp11: Fix power config

- src/mainboard/system76/adl-p/variants/darp8/overridetree.cb
Fixes system powering off under load when booting on battery.
> mb/system76/adl-p: darp8: HACK: Limit PL4 to PL2

- src/mainboard/system76/adl-p/variants/oryp9/overridetree.cb
90W for PL4 still results in power off after booting on battery.
- Limit PL4 to 72W (1.6x TDP)
- Increase PL2 back to coreboot default value of 115W
- Increase PsysPL2 to 135W
Test:
- Compile the kernel while in NVIDIA graphics mode and on battery power
- Benchmark CPU performance
> mb/system76/adl-p: oryp9: Adjust power limits again

- src/mainboard/system76/addw1/variants/addw1/overridetree.cb
- src/mainboard/system76/addw1/variants/addw2/overridetree.cb
- src/mainboard/system76/bonw14/devicetree.cb
- src/mainboard/system76/cml-u/variants/darp6/overridetree.cb
- src/mainboard/system76/gaze15/variants/gaze14/overridetree.cb
- src/mainboard/system76/gaze15/variants/gaze15/overridetree.cb
- src/mainboard/system76/gaze16/devicetree.cb
- src/mainboard/system76/lemp9/devicetree.cb
- src/mainboard/system76/oryp6/devicetree.cb
- src/mainboard/system76/oryp8/devicetree.cb
- src/mainboard/system76/tgl-u/devicetree.cb
- src/mainboard/system76/whl-u/variants/darp5/overridetree.cb
Use the new "detect" method instead of "probed". Fixes an uncommon issue where I2C HID fails to initialize the device in Linux.
Test:
- Reboot 50 times, ensure touchpad works on every boot
- Boot to Windows, ensure touchpad works and is detected as an I2C HID device
Tested on:
> mb/system76: Change touchpad detection method

- src/soc/intel/alderlake/fsp_params.c
Device 0:01.1 does not exist on ADL-P. I assume this works because the
bridged device has function 1.
Fixes the following error in Linux:
pcieport 0000:00:01.0: can't derive routing for PCI INT B
snd_hda_intel 0000:01:00.1: PCI INT B: no GSI - using ISA IRQ 10
Which in turn resolves the conflict with the PCH HDA device...again:
irq 10: nobody cared (try booting with the "irqpoll" option)
<snip>
[<00000000bf549647>] azx_interrupt [snd_hda_codec]
Disabling IRQ #10
> soc/intel/alderlake: Add IRQ for non-existent CPU PCIe device

- src/soc/intel/alderlake/chip.c
This reverts commit 884467a2b56c3ecd143055d6b338698d6a2c2a90.
Without these names, Windows fails with `INTERNAL_POWER_ERROR` (0xA0)
bugcheck with paramter 0x680. Linux reports errors for the devices, but
continues to work.
> The runtime power framework could not parse a required ACPI table
> due to it either being missing or malformed. This is usually due
> to a BIOS error.
Must be tested on galp6, which should currently be broken.
> Revert "soc/intel/alderlake: Remove some ACPI device names"

- src/soc/intel/alderlake/meminit.c
Fixes booting lemp11 with no DIMM installed.
This is a problem because Chromebooks only use CH1 for mixed topo.
> soc/intel/alderlake: Only use CH0 for mixed-topo

- src/mainboard/system76/addw1/ramstage.c
- src/mainboard/system76/adl-p/ramstage.c
- src/mainboard/system76/bonw14/ramstage.c
- src/mainboard/system76/cml-u/ramstage.c
- src/mainboard/system76/gaze15/ramstage.c
- src/mainboard/system76/gaze16/ramstage.c
- src/mainboard/system76/gaze17/ramstage.c
- src/mainboard/system76/kbl-u/ramstage.c
- src/mainboard/system76/lemp9/ramstage.c
- src/mainboard/system76/oryp5/ramstage.c
- src/mainboard/system76/oryp6/ramstage.c
- src/mainboard/system76/oryp8/ramstage.c
- src/mainboard/system76/tgl-u/ramstage.c
- src/mainboard/system76/whl-u/ramstage.c
Set the system wake-up type to power switch.
- SMBIOS requires it not be "Unknown".
- Windows hardware tests require it not be "Reserved".
Before:
```
$ sudo dmidecode -t system | grep Wake
Wake-up Type: Reserved
```
After:
```
$ sudo dmidecode -t system | grep Wake
Wake-up Type: Power Switch
```
**Note**: This is incorrect if WoL is used for power-on, as it should then report "LAN Remote".
- [SMBIOS Specification 3.6.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.6.0.pdf)
- 6.2 Required structures and data, Table 4
- 7.2.2 System - Wake-up Type
> mb/system76: Set SMBIOS wakeup type to power switch

- src/mainboard/system76/gaze16/devicetree.cb
- src/mainboard/system76/lemp9/devicetree.cb
- src/mainboard/system76/oryp8/devicetree.cb
Fixes brightness controls on Windows 10.
These were lost during the rebase.
Upstream: https://review.coreboot.org/c/coreboot/+/67636
Fixes: https://github.com/system76/firmware-open/issues/355
> mb/system76: Set gfx register

- src/mainboard/system76/adl-p/acpi/sleep.asl
Inform the EC to apply the PMC hack to allow the CPU to go to C10 during suspend.
Requies: system76/ec#305
> mb/system76/adl-p: HACK: Fix S0ix on lemp11

- src/mainboard/system76/adl-p/acpi/sleep.asl
Other boards may have the S0ix issue. Always send PTS and let the EC choose to apply the hack.
> mb/system76/adl-p: Always send signal for PMC hack

- src/mainboard/system76/adl-p/variants/darp8/overridetree.cb
- src/mainboard/system76/adl-p/variants/galp6/overridetree.cb
- src/mainboard/system76/adl-p/variants/lemp11/overridetree.cb
- src/mainboard/system76/adl-p/variants/oryp10/overridetree.cb
- src/mainboard/system76/adl-p/variants/oryp9/overridetree.cb
- src/mainboard/system76/tgl-u/variants/darp7/overridetree.cb
- src/mainboard/system76/tgl-u/variants/galp5/overridetree.cb
- src/mainboard/system76/tgl-u/variants/lemp10/overridetree.cb
This has caused nothing but issues trying to get different drives to behave correctly. Just remove it.
> tgl-u, adl-p: Remove CPU PCIe RP RTD3 config

- src/mainboard/system76/adl-p/devicetree.cb
- src/mainboard/system76/gaze17/variants/3050/overridetree.cb
- src/mainboard/system76/gaze17/variants/3060/overridetree.cb
- src/soc/intel/alderlake/Kconfig
- src/soc/intel/alderlake/Makefile.inc
- src/soc/intel/alderlake/chip.h
- src/soc/intel/alderlake/graphics.c
- Fixes brightness controls on Windows 10
- Fixes brightness controls on Linux 6.1
Might fix the issue where external displays become the default display.
Upstream: https://review.coreboot.org/c/coreboot/+/69076
> ADL: Hook up GMA brightness controls

- src/mainboard/system76/adl-p/devicetree.cb
- src/mainboard/system76/adl-p/variants/galp6/overridetree.cb
- src/mainboard/system76/tgl-u/variants/darp7/overridetree.cb
- src/mainboard/system76/tgl-u/variants/lemp10/overridetree.cb
After changing EC detection of S0ix from `CPU_C10_GATE#` to `SLP_S0#`, DevSlp blocks suspend entry. Disable it for now.
Must be tested on:
- lemp10
- lemp11
- darp7
- darp8
galp5, galp6, oryp9, and oryp10 do not support SATA.
> mb/system76/{adl-p,tgl-u}: Disable SATA DevSlp

- src/soc/intel/alderlake/acpi/serialio.asl
A previous CL ("Add missing ACPI device path names", commit d22500f0c61f8c8e10d8f4a24e3e2bf031163c07) caused some errors from the Kernel on Brya devices (see Tim's comment on patchset 8):
> ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - \_SB_.PCI0.FSPI
FSPI is defined in `src/soc/intel/alderlake/chipset.cb`: `device pci 1f.5 alias fast_spi on end`
This CL adds the corresponding FSPI device to the DSDT to prevent the error mentioned above.
Reviewed-on: https://review.coreboot.org/c/coreboot/+/69920
> soc/intel/adl/acpi: add FSPI to DSDT

- src/mainboard/system76/adl-p/variants/lemp11/overridetree.cb
Tested with the following drives:
- Crucial P5 Plus (CT500P5PSSD8)
- Kingston KC3000 (SKC3000S/512G)
- Sabrent Rocket NVMe 4.0 (SB-ROCKET-NVMEe4-500)
- Samsung 970 EVO (MZ-V7E250)
- Samsung 970 EVO Plus (MZ-V7S250)
- Samsung 980 PRO (MZ-V8P2T0)
- WD Black SN850X (WDS100T2XD0E)
- WD Blue SN580 (WDS500G2B0C)
- WD Green SN350 (WDS240G2G0C)
Test:
- PCH asserts `SLP_S0#` during suspend (power LED blinks)
- `slp_s0_residency_usec` increases after suspend
The WD Black SN850X (WDS100T2XD0E) reports corrected RX errors on suspend/resume.
> lemp11: Add CPU PCIe RTD3 and AER

- src/mainboard/system76/adl-p/variants/darp8/overridetree.cb
Tested with the following drives:
- Crucial P5 Plus (CT500P5PSSD8)
- Kingston KC3000 (SKC3000S/512G)
- Sabrent Rocket NVMe 4.0 (SB-ROCKET-NVMEe4-500)
- Samsung 970 EVO (MZ-V7E250)
- Samsung 970 EVO Plus (MZ-V7S250)
- Samsung 980 PRO (MZ-V8P2T0)
- WD Black SN850X (WDS100T2XD0E)
- WD Blue SN580 (WDS500G2B0C)
- WD Green SN350 (WDS240G2G0C)
Test:
- PCH asserts `SLP_S0#` during suspend (power LED blinks)
- `slp_s0_residency_usec` increases after suspend
> darp8: Add CPU PCIe RTD3 and AER

- src/mainboard/system76/tgl-u/variants/galp5/overridetree.cb
Tested with the following drives:
- Crucial P5 Plus (CT500P5PSSD8)
- Kingston KC3000 (SKC3000S/512G)
- Sabrent Rocket NVMe 4.0 (SB-ROCKET-NVMEe4-500)
- Samsung 970 EVO (MZ-V7E250)
- Samsung 970 EVO Plus (MZ-V7S250)
- Samsung 980 PRO (MZ-V8P2T0)
- WD Black SN850X (WDS100T2XD0E)
- WD Blue SN580 (WDS500G2B0C)
- WD Green SN350 (WDS240G2G0C)
Test:
- PCH asserts `SLP_S0#` during suspend (power LED blinks)
- `slp_s0_residency_usec` increases after suspend
> galp5: Re-add CPU PCIe RTD3

- src/soc/intel/common/block/graphics/graphics.c
Should fix Windows BSoD on RPL-HX systems
> soc/intel/common/block/graphics: Add RPL-HX IDs

- src/mainboard/system76/adl/variants/darp8/overridetree.cb
- src/mainboard/system76/adl/variants/galp6/overridetree.cb
- src/mainboard/system76/adl/variants/lemp11/overridetree.cb
- src/mainboard/system76/adl/variants/oryp10/overridetree.cb
- src/mainboard/system76/adl/variants/oryp9/overridetree.cb
- src/mainboard/system76/rpl/variants/galp7/overridetree.cb
- src/mainboard/system76/rpl/variants/lemp12/overridetree.cb
System76 EC sets PL4 values through PECI based on AC state. Remove the static PL4 values from coreboot since they won't be used. This will result in sysfs reporting the package default for PL4.
Requires: https://github.com/system76/ec/pull/353
> mb/system76: Remove PL4 values

- src/ec/system76/ec/acpi/ec.asl
Resetting the device will cause the keyboard backlight and airplane LED to lose their state.
> ec/system76/ec: Do not call reset on wake

- src/soc/intel/cannonlake/Makefile.inc
Hook up microcode from 3rdparty repo for:
- 06-a5-03 (CPUID signature: 0xa0653)
- 06-a5-05 (CPUID signature: 0xa0655)
Fixes loading microcode on system76/bonw14.
upstream: [CB:76415](https://review.coreboot.org/c/coreboot/+/76415)
> soc/intel/cannonlake: Hook up ucode for CML-S

- src/soc/intel/alderlake/cpu.c
Ref: Default values of `PmcLpmS0ixSubStateEnableMask` in FSP.
> soc/intel/adl: Fix LPM substates for RPL-HX

- src/mainboard/system76/adl/variants/darp8/overridetree.cb
- src/mainboard/system76/adl/variants/lemp11/overridetree.cb
After switching to S3, the use of RTD3 on the SATA port breaks drives exiting D3cold.
Fixes drives being unusable after suspend.
Tested on darp8 with a 970 EVO SSD and Crucial P5 in J_SSD1.
> mb/system76/adl: darp8,lemp11: Disable RTD3 on SATA port

- src/mainboard/system76/adl/variants/oryp10/overridetree.cb
According to the schematics, the components/pins for RTD3 support are not connected. The enable GPIO for components is tied directly to power and the reset GPIO is tied to `BUF_PLT_RST#`.
> oryp10: Remove RTD3 configs

- src/mainboard/system76/adl/variants/gaze17-3050/overridetree.cb
- src/mainboard/system76/adl/variants/gaze17-3060-b/overridetree.cb
According to the schematics, the components/pins for RTD3 support are not connected. The enable GPIO for components is tied directly to power and the reset GPIO is tied to `BUF_PLT_RST#`.
> gaze17: Remove RTD3 configs

- src/mainboard/system76/cml-u/Makefile.inc
When lemp9 was converted to a variant in CB:64528, the Makefile was not updated to handle the variant-specific `romstage.c`. This, as would be expected, caused memory init errors and broke boot on CML-U boards.
Tested lemp9 boots to payload again.
Fixes: 5b7b04c938f2 ("mb/system76/cml-u: Convert lemp9 to a variant")
Fixes: https://github.com/system76/firmware-open/issues/393
Upstream: [CB:76871](https://review.coreboot.org/c/coreboot/+/76871)
> mb/system76/cml-u: Fix inclusion of romstage.c

- src/mainboard/system76/adl/ramstage.c
- src/mainboard/system76/tgl-h/variants/gaze16-3050/ramstage.c
- src/mainboard/system76/tgl-h/variants/gaze16-3060/ramstage.c
- src/mainboard/system76/tgl-h/variants/oryp8/ramstage.c
Report CPU C10 state over eSPI so that the EC can use Virtual Wires to detect if PECI can be used.
Ref: https://github.com/system76/ec/pull/393
> mb/system76: Enable C10 reporting on systems using eSPI

- src/drivers/smmstore/ramstage.c
For some reason, the APM SCI to install the SMMSTORE comm buffer regularly, but not always, fails with 0x4ed on ADL. In this case, a second attempt seems to always complete successfully.
Tested on system76/darp8 and system76/galp6.
Test:
1. Add custom boot entry (`sudo bootctl install`)
2. Reboot
3. Verify custom boot entry exists (`efibootmgr`)
4. Dump coreboot log (`sudo cbmem -c`)
5. Verify SMMSTORE comm buffer was installed successfully
6. Reboot and verify 10 more times
Ref: https://github.com/system76/firmware-open/issues/437
> drivers/smmstore: Retry APM SCI if it fails

- src/mainboard/system76/rpl/variants/addw3/overridetree.cb
- src/mainboard/system76/rpl/variants/bonw15/overridetree.cb
- src/mainboard/system76/rpl/variants/serw13/overridetree.cb
See
https://ark.intel.com/content/www/us/en/ark/products/232171/intel-core-i913900hx-processor-36m-cache-up-to-5-40-ghz.html
> the i9-13900HX supports up to 128GB 5600 MT/s DDR5 memory

- src/mainboard/system76/adl/Kconfig
- src/mainboard/system76/adl/cmos-csme.default
- src/mainboard/system76/adl/variants/darp8/overridetree.cb
- src/mainboard/system76/rpl/Kconfig
- src/mainboard/system76/rpl/cmos-csme.default
- src/mainboard/system76/rpl/variants/darp9/overridetree.cb
The newer batch of these boards do not de-assert VW `PLTRST#` on S3 resume, causes the units to not power on in the EC code. Switch them to S0ix by default, but leave S3 available.
Ref: system76/firmware-open#469
> mb/system76: Enable S0ix for darp8/darp9

- src/mainboard/system76/rpl/variants/darp9/overridetree.cb
Some drives block the CPU from reaching C10 on suspend without the RTD3 config.
Fixes suspend with the following drives:
- Kingston KC3000 (SKC3000D/4096G)
- Kingston HyperX (SHPM2280P2H/240G)
- Solidigm P44 Pro (SSDPFKKW010X7)
The following drives continue to work:
- Samsung 970 Evo (MZVLB250HAHQ)
- WD Black SN770 (WDS250G3X0E)
- WD Green SN350 (WDS240G2G0C-00AJM0)
- WD Blue SN570 (WDS100T3B0C)
> mb/system76/rpl: darp9: Add SSD RTD3 configs

- src/mainboard/system76/adl/variants/darp8/overridetree.cb
- src/mainboard/system76/adl/variants/gaze17-3050/overridetree.cb
- src/mainboard/system76/adl/variants/gaze17-3060-b/overridetree.cb
- src/mainboard/system76/adl/variants/lemp11/overridetree.cb
- src/mainboard/system76/rpl/variants/gaze18/overridetree.cb
- src/mainboard/system76/rpl/variants/lemp12/overridetree.cb
The FSP may fail to detect PCIe 4.0 devices in PCIe 3.0 slots on S3 resume. This issue has only been experienced on lemp12, and only with Samsung drives, but implies it could happen on other systems or with other drives as well.
Tested on lemp12 with Samsung 980 PRO and 990 PRO drives.
> mb/system76/adl,rpl: Add timeouts for PCIe 3.0 RPs

- src/mainboard/system76/rpl/dsdt.asl
This fixes a few ACPI warnings I get on my lemp12 laptop.
[    0.157365] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.TDM0], AE_NOT_FOUND (20230628/dswload2-162)
[    0.157424] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)
[    0.157426] ACPI: Skipping parse of AML opcode: OpcodeName unavailable (0x0010)
[    0.157442] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.TRP0], AE_NOT_FOUND (20230628/dswload2-162)
[    0.157443] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)
I believe it's caused by tcss being enabled in the overridetree.cb. I went ahead and made this change for all RPL systems that have tcss enabled, but I only have hardware to verify the fix on lemp12.
> Resolve ACPI BIOS Errors for RPL systems

- src/mainboard/system76/adl/devicetree.cb
- src/mainboard/system76/adl/variants/lemp11/romstage.c
- src/mainboard/system76/adl/variants/oryp10/romstage.c
- src/mainboard/system76/adl/variants/oryp9/romstage.c
- src/mainboard/system76/rpl/devicetree.cb
Commit 2d482386182e ("soc/intel/alderlake: Set PchHdaSdiEnable for Alder Lake") hooked up a new UPD, overriding the FSP default and causing HDA init to break. Hook up the new UPD in the devicetree to restore HDA functionality.
Also remove PchHdaAudioLinkHdaEnable per board romstage, as it set in the devicetree.
- Ref: https://review.coreboot.org/c/coreboot/+/76449
- Ref: https://review.coreboot.org/c/coreboot/+/77125
> mb/system76/adl,rpl: Fix HDA codec init

- src/lib/rtc.c
- src/soc/intel/alderlake/Kconfig
- src/soc/intel/alderlake/fsp_params.c
- src/soc/intel/tigerlake/acpi/tcss.asl
- src/soc/intel/tigerlake/acpi/tcss_dma.asl
Cherry-pick the following upstream commits that have been merged since the 24.02 release:
- fb401e74da0c: [soc/intel/alderlake: Sync UPD Usb4CmMode with Kconfig](https://review.coreboot.org/c/coreboot/+/80486)
- 961ed9fe2710: [soc/intel/adl: Set slp-s0 counter frequency](https://review.coreboot.org/c/coreboot/+/80665)
- 377845a9d4f3: [soc/intel/tigerlake: Fix processor hang while plug unplug of TBT device](https://review.coreboot.org/c/coreboot/+/80718)
- 354a54ac84a9: [soc/intel/tigerlake: Remove IOM Mctp command from TCSS ASL](https://review.coreboot.org/c/coreboot/+/80719)
- adf042f6c61e: [lib/rtc: Fix off-by-one error in February day count in leap year](https://review.coreboot.org/c/coreboot/+/80790)
> Pick upstream SoC and RTC fixes

- src/mainboard/system76/rpl/variants/oryp12/overridetree.cb
This is the same issue that affects serw13. May be related to the use of the DTBT driver?
> mb/system76/rpl: oryp12: Disable AER on TBT port

- src/mainboard/system76/addw1/cmos.layout
- src/mainboard/system76/adl/cmos.layout
- src/mainboard/system76/bonw14/cmos.layout
- src/mainboard/system76/cml-u/cmos.layout
- src/mainboard/system76/gaze15/cmos.layout
- src/mainboard/system76/kbl-u/cmos.layout
- src/mainboard/system76/mtl/cmos.layout
- src/mainboard/system76/oryp5/cmos.layout
- src/mainboard/system76/oryp6/cmos.layout
- src/mainboard/system76/rpl/cmos.layout
- src/mainboard/system76/tgl-h/cmos.layout
- src/mainboard/system76/tgl-u/cmos.layout
- src/mainboard/system76/whl-u/cmos.layout
Use the default position for ramtop and exclude it from the checksum. Fixes invalid checksum after caching ramtop causing things like disabling CSME to not work.
upstream: [CB:81641](https://review.coreboot.org/c/coreboot/+/81641)
> mb/system76: Update CMOS layouts

- src/soc/intel/alderlake/fsp_params.c
UsbTcPortEn is configured based on pointers to tcss_usb3_port1, which is part of the ACPI driver.
This is illogical, as the port might need to be enabled, and the ACPI not needed or included. Change this so it's configured based on the tcss_port[x] in devicetree.
Tested by connecting a USB 3.0 hub, and checking that Linux correctly identifies a new USB 3.0 device.
Change-Id: I07ef0759057f7f40210766a73643c9ccf1dc986d
Reviewed-on: https://review.coreboot.org/c/coreboot/+/82058
> soc/intel/alderlake: Set UsbTcPortEn based on tcss_port[x]

- src/soc/intel/alderlake/romstage/fsp_params.c
[ upstream commit ca5254acc0d55199254a270496c955249ad244d1 ]
The UsbTcPortEn UPD for FSP-S is being set in ramstage, however the equivalent FSP-M UPD, the UsbTcPortEnPreMem, was not being set. Following the Meteor Lake example, set the UsbTcPortEnPreMem UPD as well for Alder Lake.
Setting this FSP-M UPD will cause FSP to properly program sideband use BSSB_LSx pins for the enabled Type-C ports. Required for proper DCI debug and TCSS initialization flow.
Reviewed-on: https://review.coreboot.org/c/coreboot/+/80500
> soc/alderlake/romstage: Set UsbTcPortEnPreMem UPD based on devicetree

- src/drivers/intel/dtbt/dtbt.c
- Add commands defined for TR, MR, and BR
- Wait on mailbox commands by ms instead of us
- Split up, reformat acpigen
- Allow passing data to commands
- Remove unnecessary `GET_SECURITY_LEVEL` calls
No behavior change; This does not fix using Barlow Ridge.
Verify a model with Maple Ridge still works.
> drivers/intel/dtbt: Update based on feedback

- src/mainboard/system76/mtl/devicetree.cb
The fuck did Intel add now?
TODO: Check if it's detected/works with the NPU driver or something.
Ref: https://github.com/system76/firmware-open/issues/580
> mb/system76/mtl: Enable NPU

- src/soc/intel/alderlake/Makefile.mk
Cherry-pick:
- 148bc36c6de2 ("3rdparty/intel-microcode: Update submodule to upstream main")
- 9dcfad722cf2 ("soc/intel/raptorlake: Fall back to Intel microcode repo")
- 672c36d71fe0 ("3rdparty/intel-microcode: Update submodule to upstream main")
- 02cbfaa20120 ("3rdparty/intel-microcode: Update submodule to upstream main")
Ref:
- https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20241112
> Update Intel microcode to 2024-11-12 release

- src/mainboard/system76/meer9/bootblock.c
- src/mainboard/system76/meer9/cmos.default
- src/mainboard/system76/meer9/cmos.layout
Configure SuperIO for BIOS control of power loss behavior and add CMOS option to allow user control.
Enum 1 is used instead of 7 as the `Keep` option does not seem to work on meer9. The same setting via SIO control (`CRE4`) does work, though.
With default value of `Disable`:
- Unit remains off after unplugging and plugging AC power while on or off
With value of `Enable`:
- Unit turns back on after unplugging and plugging AC power while on or off
> mb/system76/meer9: Add `power_on_after_fail`

- src/mainboard/system76/meer9/bootblock.c
- src/mainboard/system76/meer9/devicetree.cb
- Curve increases more gradually
- TCC is adjusted to 99C
- Critical temperature is 105C, above TCC point
- Curve reaches 100% gradually at 99C instead of triggering critical fan duty at 95C
> Improvements to the meer9 fan curve

- src/drivers/gfx/nvidia/Kconfig
- src/drivers/gfx/nvidia/acpi/common/nvpcf.asl
- src/drivers/gfx/nvidia/nvidia.c
- Require ACPI for the driver
- Add more inline docs
- Add `_STA` method
- Update field names to better match names from Clevo dumps/DG samples
- Add fields for v2.4 (unimplemented)
- Add `TGPA` field for `UPDATE_DYNAMIC_PARAMS`
- Match proprietary behavior for "Set Controller Status"
- Add objects for disabling boost on AC/DC
- Add debug logs for unimplemented functions
> drivers/gfx/nvidia: NVPCF updates

- src/mainboard/system76/rpl/variants/gaze20/overridetree.cb
- Does 6400 MT/s work, or should it be limited to 5600 MT/s like other models?
- Should other models be increased to 6400 MT/s?
> mb/system76/rpl: gaze20: Support up to 6400 MT/s memory
